project_id = "xgisixdxffyvwsfsnjsu"

[auth.web3.solana]
enabled = true

[functions.purchase-vices]
verify_jwt = true

[functions.get-team-wallet]
verify_jwt = false

[functions.get-rpc-url]
verify_jwt = false
