// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xgisixdxffyvwsfsnjsu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhnaXNpeGR4ZmZ5dndzZnNuanN1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTk4MTg0NTgsImV4cCI6MjA3NTM5NDQ1OH0.Asxw-PCtM7hQQpjhPbzPYiXue_EEwq4GPYyo9LZySR0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});